INSERT INTO libros VALUES
(1, 'HARRY POTTER Y EL PRISIONERO DE AZKABAN', 'J.K ROWLING',
'SALAMANDRA', '2013-10-08', 'INFANTIL'),
(2, 'EL GRAN LABERINTO', 'FERNANDO SABATER PEREZ', 'ARIEL',
'2012-10-16', 'FICCION'),
(3, 'ROMEO Y JULIETA', 'WILLIAM SHAKESPEARE', 'SALAMANDRA',
'2014-07-18', 'ROMANTICA'),
(4, 'LA CARTA ESFERICA', 'ARTURO PEREZ LOPEZ', 'SALAMANDRA',
'2011-04-08', 'FICCION'),
(5, 'EL CODIGO DA VINCI', 'DAN BROWN', 'ARIEL', '2010-10-20',
'FICCION');

INSERT INTO usuarios VALUES
(1, 'admin', '456'), (2, 'itic', 'itic');